import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ folder structure: the hub landing
 * page (docs/index.md) plus one category per product (docs/<product>/), each
 * ordered by its _category_.json and the docs' sidebar_position frontmatter.
 * Adding a product is just adding a folder — no edits here.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
